apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz-webhook
  labels:
    app.kubernetes.io/name: authz-webhook
    app.kubernetes.io/part-of: auth-provider-openfga
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authz-webhook
      app.kubernetes.io/part-of: auth-provider-openfga
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: authz-webhook
        app.kubernetes.io/part-of: auth-provider-openfga
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: authz-webhook
          image: ghcr.io/milo-os/openfga-provider:latest
          imagePullPolicy: IfNotPresent
          args:
            - authz-webhook
            - --metrics-bind-address=:8080
            - --webhook-port=8090
            - --cert-dir=/etc/webhook/serving-certs
            - --cert-file=tls.crt
            - --key-file=tls.key
            - --openfga-api-url=$(OPENFGA_API_URL)
            - --openfga-store-id=$(OPENFGA_STORE_ID)
            - --configmap-name=$(CONFIGMAP_NAME)
            - --configmap-namespace=$(CONFIGMAP_NAMESPACE)
            - --health-probe-bind-address=:8081
          env:
            - name: OPENFGA_API_URL
              value: openfga.openfga-system.svc.cluster.local:8081
            # Fake OpenFGA store ID that should be replaced with an actual store
            # ID that's created in the OpenFGA server.
            - name: OPENFGA_STORE_ID
              value: 01JVTBDT6NJ541P1JBT22GX4PR
            - name: CONFIGMAP_NAME
              value: openfga-authorization-model
            - name: CONFIGMAP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FEATURE_GATES
              value: ""
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health-probe
              protocol: TCP
            - containerPort: 8090
              name: webhook
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            failureThreshold: 30
            periodSeconds: 2
          volumeMounts: []
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi

      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes: []
