package openfga

import (
	"context"
	"encoding/hex"
	"fmt"
	"hash/fnv"
	"sort"
	"strings"

	"github.com/google/go-cmp/cmp"
	openfgav1 "github.com/openfga/api/proto/openfga/v1"
	iamdatumapiscomv1alpha1 "go.miloapis.com/milo/pkg/apis/iam/v1alpha1"
	"google.golang.org/protobuf/testing/protocmp"
	"google.golang.org/protobuf/types/known/wrapperspb"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
)

type AuthorizationModelReconciler struct {
	StoreID string
	OpenFGA openfgav1.OpenFGAServiceClient
}

// getAuthorizationModelComparisonOptions returns the standardized cmp.Option slice for comparing authorization models
// with options to ignore ordering differences and the OpenFGA-assigned id field
func getAuthorizationModelComparisonOptions() []cmp.Option {
	return []cmp.Option{
		// Use protocmp.Transform for proper protobuf message comparison
		protocmp.Transform(),
		// Ignore the id field since it's assigned by OpenFGA and not semantically meaningful
		protocmp.IgnoreFields(&openfgav1.AuthorizationModel{}, "id"),
		// Sort repeated fields that can have different orderings without changing semantics
		protocmp.SortRepeated(func(a, b *openfgav1.TypeDefinition) bool {
			return a.Type < b.Type
		}),
		protocmp.SortRepeated(func(a, b *openfgav1.RelationReference) bool {
			return a.Type < b.Type
		}),
	}
}

// authorizationModelsEqual compares two authorization models using go-cmp with protocmp
// and options to ignore ordering differences that don't affect semantics
func authorizationModelsEqual(current, merged *openfgav1.AuthorizationModel) bool {
	if current == nil && merged == nil {
		return true
	}
	if current == nil || merged == nil {
		return false
	}

	return cmp.Equal(current, merged, getAuthorizationModelComparisonOptions()...)
}

func (r *AuthorizationModelReconciler) ReconcileAuthorizationModel(ctx context.Context, protectedResources []iamdatumapiscomv1alpha1.ProtectedResource) error {
	log := logf.FromContext(ctx).WithValues("component", "AuthorizationModelReconciler")

	currentAuthorizationModel, err := r.getCurrentAuthorizationModel(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current authorization model: %w", err)
	}

	newAuthorizationModel, err := r.createExpectedAuthorizationModel(protectedResources)
	if err != nil {
		return fmt.Errorf("failed to create new authorization model: %w", err)
	}

	mergedAuthorizationModel := &openfgav1.AuthorizationModel{
		SchemaVersion: newAuthorizationModel.SchemaVersion,
		// Conditions are not dynamically generated by the IAM system so we can
		// safely set the conditions to whatever is already in the authorization
		// model.
		//
		// TODO: Update when conditions are dynamically created by the IAM system.
		Conditions: currentAuthorizationModel.Conditions,
	}

	// Create a map to track existing types and prevent duplicates.
	// Under the direct-permission model the IAM system manages InternalUser and
	// InternalUserGroup only. All other types (InternalRole, RoleBinding, Root)
	// are no longer generated.
	existingTypes := make(map[string]bool)

	iamSystemTypes := map[string]bool{
		TypeInternalUser:      true,
		TypeInternalUserGroup: true,
		// Legacy types that are now managed (and regenerated) by this reconciler
		// so that stale definitions from previous model versions are replaced.
		TypeInternalRole: true,
		TypeRoleBinding:  true,
		TypeRoot:         true,
	}

	// Go through the existing type definitions and add any that were provided
	// through the OpenFGA schema language, excluding IAM system managed types.
	for _, typeDefinition := range currentAuthorizationModel.TypeDefinitions {
		// Skip IAM system managed types as they will be regenerated
		if iamSystemTypes[typeDefinition.Type] {
			continue
		}

		// The type definitions added by the IAM system will always be in the
		// format `{service_name}/{resource_type}`. Since this format is only
		// valid when building the resource model in JSON, we can safely
		// guarantee that type definitions added by Datum OS through the OpenFGA
		// schema language will never contain a "/" character.
		if len(strings.Split(typeDefinition.Type, "/")) == 1 {
			mergedAuthorizationModel.TypeDefinitions = append(mergedAuthorizationModel.TypeDefinitions, typeDefinition)
			existingTypes[typeDefinition.Type] = true
		}
	}

	// Add new type definitions, but only if they don't already exist
	for _, typeDefinition := range newAuthorizationModel.TypeDefinitions {
		if !existingTypes[typeDefinition.Type] {
			mergedAuthorizationModel.TypeDefinitions = append(mergedAuthorizationModel.TypeDefinitions, typeDefinition)
			existingTypes[typeDefinition.Type] = true
		}
	}

	// Compare using go-cmp with protocmp for proper protobuf comparison
	if authorizationModelsEqual(currentAuthorizationModel, mergedAuthorizationModel) {
		log.Info("Authorization model is already up to date, skipping write operation")
		return nil
	}

	log.Info("Authorization model has changed, updating OpenFGA store",
		"currentTypeCount", len(currentAuthorizationModel.TypeDefinitions),
		"mergedTypeCount", len(mergedAuthorizationModel.TypeDefinitions))

	// Add debugging diff output to understand what's different
	if diff := cmp.Diff(currentAuthorizationModel, mergedAuthorizationModel, getAuthorizationModelComparisonOptions()...); diff != "" {
		log.Info("Authorization model diff detected", "diff", diff)
	}

	_, err = r.OpenFGA.WriteAuthorizationModel(ctx, &openfgav1.WriteAuthorizationModelRequest{
		StoreId:         r.StoreID,
		SchemaVersion:   mergedAuthorizationModel.SchemaVersion,
		TypeDefinitions: mergedAuthorizationModel.TypeDefinitions,
		Conditions:      mergedAuthorizationModel.Conditions,
	})
	if err != nil {
		return fmt.Errorf("failed to reconcile authorization model: %w", err)
	}

	return nil
}

func (r *AuthorizationModelReconciler) getCurrentAuthorizationModel(ctx context.Context) (*openfgav1.AuthorizationModel, error) {
	models, err := r.OpenFGA.ReadAuthorizationModels(ctx, &openfgav1.ReadAuthorizationModelsRequest{
		StoreId: r.StoreID,
		// Only request the first result because it'll always be the latest
		// authorization model that was created for the store.
		PageSize: wrapperspb.Int32(1),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list authorization models: %w", err)
	}

	if len(models.AuthorizationModels) == 0 {
		// No authorization model has been created yet so we'll just return an
		// empty model.
		return &openfgav1.AuthorizationModel{}, nil
	}

	// Retrieve the full authorization model definition
	resp, err := r.OpenFGA.ReadAuthorizationModel(ctx, &openfgav1.ReadAuthorizationModelRequest{
		StoreId: r.StoreID,
		Id:      models.AuthorizationModels[0].Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get authorization model: %w", err)
	}

	return resp.AuthorizationModel, nil
}

func (r *AuthorizationModelReconciler) createExpectedAuthorizationModel(protectedResources []iamdatumapiscomv1alpha1.ProtectedResource) (*openfgav1.AuthorizationModel, error) {
	// If no ProtectedResources exist, return a minimal authorization model
	if len(protectedResources) == 0 {
		return getMinimalAuthorizationModel(), nil
	}

	// Build the resource hierarchy
	resourceGraph, err := getResourceGraph(protectedResources)
	if err != nil {
		return nil, fmt.Errorf("failed to get resource graph: %v", err)
	}

	// Calculate hierarchical permissions for each resource type
	hierarchicalPermissions := calculateHierarchicalPermissions(resourceGraph)

	// Create base IAM type definitions in deterministic order. Under the
	// direct-permission model only InternalUser and InternalUserGroup are
	// needed as top-level IAM types. InternalRole, RoleBinding, and Root are
	// no longer part of the model.
	typeDefinitions := []*openfgav1.TypeDefinition{
		getUserTypeDefinition(),
		getUserGroupTypeDefinition(),
	}

	// Get resource type definitions and add them in sorted order
	resourceTypeDefinitions := getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, resourceGraph)

	// Sort resource type definition keys for deterministic ordering
	sortedResourceTypes := make([]string, 0, len(resourceTypeDefinitions))
	for resourceType := range resourceTypeDefinitions {
		sortedResourceTypes = append(sortedResourceTypes, resourceType)
	}
	sort.Strings(sortedResourceTypes)

	// Add resource type definitions in sorted order
	for _, resourceType := range sortedResourceTypes {
		typeDefinitions = append(typeDefinitions, resourceTypeDefinitions[resourceType])
	}

	return &openfgav1.AuthorizationModel{
		SchemaVersion:   "1.2",
		TypeDefinitions: typeDefinitions,
	}, nil
}

func getResourceParentRelatedTypes(parents []string) (relations []*openfgav1.RelationReference) {
	for _, parent := range parents {
		relations = append(relations, &openfgav1.RelationReference{
			Type: parent,
		})
	}
	return
}

// getResourceTypeDefinition builds the OpenFGA TypeDefinition for a resource
// under the direct-permission model.
//
// Each hashed-permission relation accepts:
//   - A directly-assigned InternalUser
//   - A directly-assigned InternalUserGroup (resolved via its "member" relation)
//   - Permissions inherited from the parent resource (via the "parent" tupleset)
//
// This replaces the previous RoleBinding/InternalRole intersection that
// required ~27 datastore reads per Check. With direct tuples a Check resolves
// in 1-3 reads.
func getResourceTypeDefinition(permissions []string, resourceNode *resourceGraphNode) *openfgav1.TypeDefinition {
	typeDefinition := &openfgav1.TypeDefinition{
		Type: resourceNode.ResourceType,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: strings.Split(resourceNode.ResourceType, "/")[0],
		},
		Relations: map[string]*openfgav1.Userset{},
	}

	// Only create a parent reference if the resource has parent relationships.
	if len(resourceNode.ParentResources) > 0 {
		typeDefinition.Metadata.Relations[RelationParent] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: getResourceParentRelatedTypes(resourceNode.ParentResources),
		}
		typeDefinition.Relations[RelationParent] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{},
		}
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)

		// Build the union of assignment sources for this permission relation.
		// Start with direct user/group assignment (This).
		permChildren := []*openfgav1.Userset{
			// Direct assignment: an InternalUser or InternalUserGroup#member tuple
			// grants this permission on the resource directly.
			{Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}}},
		}

		// If the resource has parents, add permission inheritance from the parent.
		if len(resourceNode.ParentResources) > 0 {
			permChildren = append(permChildren, &openfgav1.Userset{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset: &openfgav1.ObjectRelation{
							Relation: RelationParent,
						},
						ComputedUserset: &openfgav1.ObjectRelation{
							Relation: hashedPermission,
						},
					},
				},
			})
		}

		// The relation metadata declares which user types may be directly assigned.
		typeDefinition.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				// Individual users
				{Type: TypeInternalUser},
				// Group members (resolved transitively via InternalUserGroup#member)
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}

		if len(permChildren) == 1 {
			// No parent: just use This directly (avoids unnecessary Union wrapper).
			typeDefinition.Relations[hashedPermission] = permChildren[0]
		} else {
			typeDefinition.Relations[hashedPermission] = &openfgav1.Userset{
				Userset: &openfgav1.Userset_Union{
					Union: &openfgav1.Usersets{
						Child: permChildren,
					},
				},
			}
		}
	}

	return typeDefinition
}

func getMinimalAuthorizationModel() *openfgav1.AuthorizationModel {
	// Return a minimal authorization model with just InternalUser and
	// InternalUserGroup when no ProtectedResources exist.
	return &openfgav1.AuthorizationModel{
		SchemaVersion: "1.2",
		TypeDefinitions: []*openfgav1.TypeDefinition{
			getUserTypeDefinition(),
			getUserGroupTypeDefinition(),
		},
	}
}

func getUserTypeDefinition() *openfgav1.TypeDefinition {
	return &openfgav1.TypeDefinition{
		Type: TypeInternalUser,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{},
	}
}

func getUserGroupTypeDefinition() *openfgav1.TypeDefinition {
	return &openfgav1.TypeDefinition{
		Type: TypeInternalUserGroup,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationMember: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{
							Type: TypeInternalUser,
						},
					},
				},
				RelationAssignee: {
					DirectlyRelatedUserTypes: nil,
				},
			},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationMember: {
				Userset: &openfgav1.Userset_This{
					This: &openfgav1.DirectUserset{},
				},
			},
			RelationAssignee: {
				Userset: &openfgav1.Userset_ComputedUserset{
					ComputedUserset: &openfgav1.ObjectRelation{
						Relation: RelationMember,
					},
				},
			},
		},
	}
}

func hashPermission(permission string) string {
	hasher := fnv.New32a()
	//revive:disable-next-line:unhandled-error a
	hasher.Write([]byte(permission))

	return hex.EncodeToString(hasher.Sum(nil))
}

func HashPermission(permission string) string {
	return hashPermission(permission)
}

// calculateHierarchicalPermissions calculates which permissions each resource type should have
// based on its position in the hierarchy. Each resource gets its own permissions plus
// all permissions from its descendants (children, grandchildren, etc.)
func calculateHierarchicalPermissions(rootNode *resourceGraphNode) map[string][]string {
	hierarchicalPermissions := make(map[string][]string)

	// Traverse the entire graph and calculate permissions for each node
	calculatePermissionsForNode(rootNode, hierarchicalPermissions)

	return hierarchicalPermissions
}

// calculatePermissionsForNode recursively calculates permissions for a node and all its descendants
func calculatePermissionsForNode(node *resourceGraphNode, permissionsMap map[string][]string) []string {
	if node == nil {
		return []string{}
	}

	// Skip the root IAM node as it's handled separately
	if node.ResourceType == TypeRoot {
		// Process children but don't assign permissions to the IAM root
		for _, child := range node.ChildResources {
			calculatePermissionsForNode(child, permissionsMap)
		}
		return []string{}
	}

	// If we've already calculated permissions for this node, return them
	if permissions, exists := permissionsMap[node.ResourceType]; exists {
		return permissions
	}

	// Start with this node's direct permissions
	nodePermissions := make([]string, len(node.DirectPermissions))
	copy(nodePermissions, node.DirectPermissions)

	// Add permissions from all child resources
	for _, child := range node.ChildResources {
		childPermissions := calculatePermissionsForNode(child, permissionsMap)
		nodePermissions = append(nodePermissions, childPermissions...)
	}

	// Remove duplicates
	nodePermissions = removeDuplicatePermissions(nodePermissions)

	// Store the calculated permissions
	permissionsMap[node.ResourceType] = nodePermissions

	return nodePermissions
}

// removeDuplicatePermissions removes duplicate permission strings from a slice
func removeDuplicatePermissions(permissions []string) []string {
	seen := make(map[string]bool)
	result := []string{}

	for _, permission := range permissions {
		if !seen[permission] {
			seen[permission] = true
			result = append(result, permission)
		}
	}

	return result
}

// getResourceTypeDefinitionsWithHierarchicalPermissions creates type definitions with
// permissions assigned based on hierarchical relationships
func getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions map[string][]string, node *resourceGraphNode) map[string]*openfgav1.TypeDefinition {
	types := map[string]*openfgav1.TypeDefinition{}

	// Process the current node
	if node.ResourceType != TypeRoot {
		permissions := hierarchicalPermissions[node.ResourceType]
		if permissions == nil {
			permissions = []string{} // Default to empty if not found
		}
		types[node.ResourceType] = getResourceTypeDefinition(permissions, node)
	}

	// Process all child nodes
	for _, child := range node.ChildResources {
		childTypes := getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, child)
		for k, v := range childTypes {
			types[k] = v
		}
	}

	return types
}
