package openfga

import (
	"context"
	"encoding/hex"
	"fmt"
	"hash/fnv"
	"sort"
	"strings"

	"github.com/google/go-cmp/cmp"
	openfgav1 "github.com/openfga/api/proto/openfga/v1"
	iamdatumapiscomv1alpha1 "go.miloapis.com/milo/pkg/apis/iam/v1alpha1"
	"google.golang.org/protobuf/testing/protocmp"
	"google.golang.org/protobuf/types/known/wrapperspb"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	// AuthorizationModelConfigMapName is the default name for the ConfigMap
	// that holds the latest authorization model ID. Used as the flag default.
	AuthorizationModelConfigMapName = "openfga-authorization-model"

	// AuthorizationModelIDKey is the key within the ConfigMap's data map that
	// stores the model ID string.
	AuthorizationModelIDKey = "model-id"
)

type AuthorizationModelReconciler struct {
	StoreID string
	OpenFGA openfgav1.OpenFGAServiceClient

	// K8sClient is used to create/update the ConfigMap that holds the current
	// authorization model ID. When nil, the ConfigMap write is skipped.
	K8sClient client.Client
	// Namespace is the Kubernetes namespace in which the ConfigMap is created.
	Namespace string
	// ConfigMapName is the name of the ConfigMap that stores the model ID.
	// Defaults to DefaultAuthorizationModelConfigMapName if empty.
	ConfigMapName string
}

// getAuthorizationModelComparisonOptions returns the standardized cmp.Option slice for comparing authorization models
// with options to ignore ordering differences and the OpenFGA-assigned id field
func getAuthorizationModelComparisonOptions() []cmp.Option {
	return []cmp.Option{
		protocmp.Transform(),
		protocmp.IgnoreFields(&openfgav1.AuthorizationModel{}, "id"),
		protocmp.SortRepeated(func(a, b *openfgav1.TypeDefinition) bool {
			return a.Type < b.Type
		}),
		protocmp.SortRepeated(func(a, b *openfgav1.RelationReference) bool {
			if a.Type != b.Type {
				return a.Type < b.Type
			}
			return a.GetRelation() < b.GetRelation()
		}),
		protocmp.SortRepeated(func(a, b *openfgav1.Userset) bool {
			return fmt.Sprint(a) < fmt.Sprint(b)
		}),
	}
}

// authorizationModelsEqual compares two authorization models using go-cmp with protocmp
// and options to ignore ordering differences that don't affect semantics
func authorizationModelsEqual(current, merged *openfgav1.AuthorizationModel) bool {
	if current == nil && merged == nil {
		return true
	}
	if current == nil || merged == nil {
		return false
	}

	return cmp.Equal(current, merged, getAuthorizationModelComparisonOptions()...)
}

func (r *AuthorizationModelReconciler) ReconcileAuthorizationModel(ctx context.Context, protectedResources []iamdatumapiscomv1alpha1.ProtectedResource) error {
	log := logf.FromContext(ctx).WithValues("component", "AuthorizationModelReconciler")

	currentAuthorizationModel, err := r.getCurrentAuthorizationModel(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current authorization model: %w", err)
	}

	newAuthorizationModel, err := r.createExpectedAuthorizationModel(protectedResources)
	if err != nil {
		return fmt.Errorf("failed to create new authorization model: %w", err)
	}

	mergedAuthorizationModel := &openfgav1.AuthorizationModel{
		SchemaVersion: newAuthorizationModel.SchemaVersion,
		// Conditions are not dynamically generated by the IAM system so we can
		// safely set the conditions to whatever is already in the authorization
		// model.
		//
		// TODO: Update when conditions are dynamically created by the IAM system.
		Conditions: currentAuthorizationModel.Conditions,
	}

	// Create a map to track existing types and prevent duplicates.
	// The IAM system manages InternalUser, InternalUserGroup, and Root.
	existingTypes := make(map[string]bool)

	iamSystemTypes := map[string]bool{
		TypeInternalUser:      true,
		TypeInternalUserGroup: true,
		TypeRoot:              true,
	}

	// Go through the existing type definitions and add any that were provided
	// through the OpenFGA schema language, excluding IAM system managed types.
	for _, typeDefinition := range currentAuthorizationModel.TypeDefinitions {
		if iamSystemTypes[typeDefinition.Type] {
			continue
		}

		// The type definitions added by the IAM system will always be in the
		// format `{service_name}/{resource_type}`. Since this format is only
		// valid when building the resource model in JSON, we can safely
		// guarantee that type definitions added by Datum OS through the OpenFGA
		// schema language will never contain a "/" character.
		if len(strings.Split(typeDefinition.Type, "/")) == 1 {
			mergedAuthorizationModel.TypeDefinitions = append(mergedAuthorizationModel.TypeDefinitions, typeDefinition)
			existingTypes[typeDefinition.Type] = true
		}
	}

	// Add new type definitions, but only if they don't already exist
	for _, typeDefinition := range newAuthorizationModel.TypeDefinitions {
		if !existingTypes[typeDefinition.Type] {
			mergedAuthorizationModel.TypeDefinitions = append(mergedAuthorizationModel.TypeDefinitions, typeDefinition)
			existingTypes[typeDefinition.Type] = true
		}
	}

	// Compare using go-cmp with protocmp for proper protobuf comparison
	if authorizationModelsEqual(currentAuthorizationModel, mergedAuthorizationModel) {
		log.Info("Authorization model is already up to date, skipping write operation")
		// Even when the model is unchanged we still want the ConfigMap to
		// reflect the current model ID (e.g. after a controller restart or
		// a fresh cluster where the ConfigMap was never created).
		if r.K8sClient != nil && r.Namespace != "" && currentAuthorizationModel.GetId() != "" {
			if cmErr := r.writeModelIDToConfigMap(ctx, currentAuthorizationModel.GetId()); cmErr != nil {
				log.Error(cmErr, "failed to write authorization model ID to ConfigMap (no-op path)",
					"model_id", currentAuthorizationModel.GetId())
			}
		}
		return nil
	}

	log.Info("Authorization model has changed, updating OpenFGA store",
		"currentTypeCount", len(currentAuthorizationModel.TypeDefinitions),
		"mergedTypeCount", len(mergedAuthorizationModel.TypeDefinitions))

	if diff := cmp.Diff(currentAuthorizationModel, mergedAuthorizationModel, getAuthorizationModelComparisonOptions()...); diff != "" {
		log.Info("Authorization model diff detected", "diff", diff)
	}

	writeResp, err := r.OpenFGA.WriteAuthorizationModel(ctx, &openfgav1.WriteAuthorizationModelRequest{
		StoreId:         r.StoreID,
		SchemaVersion:   mergedAuthorizationModel.SchemaVersion,
		TypeDefinitions: mergedAuthorizationModel.TypeDefinitions,
		Conditions:      mergedAuthorizationModel.Conditions,
	})
	if err != nil {
		return fmt.Errorf("failed to reconcile authorization model: %w", err)
	}

	if r.K8sClient != nil && r.Namespace != "" && writeResp.GetAuthorizationModelId() != "" {
		if cmErr := r.writeModelIDToConfigMap(ctx, writeResp.GetAuthorizationModelId()); cmErr != nil {
			log.Error(cmErr, "failed to write authorization model ID to ConfigMap",
				"model_id", writeResp.GetAuthorizationModelId())
		}
	}

	return nil
}

// writeModelIDToConfigMap creates or updates the openfga-authorization-model
// ConfigMap in the configured namespace with the given model ID.
func (r *AuthorizationModelReconciler) writeModelIDToConfigMap(ctx context.Context, modelID string) error {
	cmName := r.ConfigMapName

	log := logf.FromContext(ctx).WithValues("component", "AuthorizationModelReconciler", "model_id", modelID)

	cm := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      cmName,
			Namespace: r.Namespace,
		},
	}

	result, err := controllerutil.CreateOrUpdate(ctx, r.K8sClient, cm, func() error {
		if cm.Data == nil {
			cm.Data = make(map[string]string)
		}
		cm.Data[AuthorizationModelIDKey] = modelID
		return nil
	})
	if err != nil {
		return fmt.Errorf("failed to create/update authorization model ConfigMap: %w", err)
	}

	log.Info("authorization model ID written to ConfigMap",
		"configmap", cmName,
		"namespace", r.Namespace,
		"result", result,
	)
	return nil
}

func (r *AuthorizationModelReconciler) getCurrentAuthorizationModel(ctx context.Context) (*openfgav1.AuthorizationModel, error) {
	models, err := r.OpenFGA.ReadAuthorizationModels(ctx, &openfgav1.ReadAuthorizationModelsRequest{
		StoreId:  r.StoreID,
		PageSize: wrapperspb.Int32(1),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list authorization models: %w", err)
	}

	if len(models.AuthorizationModels) == 0 {
		return &openfgav1.AuthorizationModel{}, nil
	}

	resp, err := r.OpenFGA.ReadAuthorizationModel(ctx, &openfgav1.ReadAuthorizationModelRequest{
		StoreId: r.StoreID,
		Id:      models.AuthorizationModels[0].Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get authorization model: %w", err)
	}

	return resp.AuthorizationModel, nil
}

func (r *AuthorizationModelReconciler) createExpectedAuthorizationModel(protectedResources []iamdatumapiscomv1alpha1.ProtectedResource) (*openfgav1.AuthorizationModel, error) {
	if len(protectedResources) == 0 {
		return getMinimalAuthorizationModel(), nil
	}

	sortedPRs := make([]iamdatumapiscomv1alpha1.ProtectedResource, len(protectedResources))
	copy(sortedPRs, protectedResources)
	sort.Slice(sortedPRs, func(i, j int) bool {
		keyI := sortedPRs[i].Spec.ServiceRef.Name + "/" + sortedPRs[i].Spec.Kind
		keyJ := sortedPRs[j].Spec.ServiceRef.Name + "/" + sortedPRs[j].Spec.Kind
		if keyI != keyJ {
			return keyI < keyJ
		}
		return sortedPRs[i].Name < sortedPRs[j].Name
	})

	resourceGraph, err := getResourceGraph(sortedPRs)
	if err != nil {
		return nil, fmt.Errorf("failed to get resource graph: %v", err)
	}

	hierarchicalPermissions := calculateHierarchicalPermissions(resourceGraph)

	// Collect all unique permissions for the Root type.
	allPermsSet := make(map[string]struct{})
	for _, perms := range hierarchicalPermissions {
		for _, p := range perms {
			allPermsSet[p] = struct{}{}
		}
	}
	allPermissions := make([]string, 0, len(allPermsSet))
	for p := range allPermsSet {
		allPermissions = append(allPermissions, p)
	}
	sort.Strings(allPermissions)

	typeDefinitions := []*openfgav1.TypeDefinition{
		getUserTypeDefinition(),
		getUserGroupTypeDefinition(),
	}

	// Direct-permission model: resource types with direct user/group
	// relations and a simplified Root type.
	resourceTypeDefinitions := getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, resourceGraph)

	sortedResourceTypes := make([]string, 0, len(resourceTypeDefinitions))
	for resourceType := range resourceTypeDefinitions {
		sortedResourceTypes = append(sortedResourceTypes, resourceType)
	}
	sort.Strings(sortedResourceTypes)

	for _, resourceType := range sortedResourceTypes {
		typeDefinitions = append(typeDefinitions, resourceTypeDefinitions[resourceType])
	}

	typeDefinitions = append(typeDefinitions, getRootTypeDefinition(allPermissions))

	return &openfgav1.AuthorizationModel{
		SchemaVersion:   "1.2",
		TypeDefinitions: typeDefinitions,
	}, nil
}

func getResourceParentRelatedTypes(parents []string) (relations []*openfgav1.RelationReference) {
	sortedParents := make([]string, len(parents))
	copy(sortedParents, parents)
	sort.Strings(sortedParents)
	for _, parent := range sortedParents {
		relations = append(relations, &openfgav1.RelationReference{
			Type: parent,
		})
	}
	return
}

// getResourceTypeDefinition builds the OpenFGA TypeDefinition for a resource
// for the authorization model.
func getResourceTypeDefinition(permissions []string, resourceNode *resourceGraphNode) *openfgav1.TypeDefinition {
	typeDefinition := &openfgav1.TypeDefinition{
		Type: resourceNode.ResourceType,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: strings.Split(resourceNode.ResourceType, "/")[0],
		},
		Relations: map[string]*openfgav1.Userset{},
	}

	if len(resourceNode.ParentResources) > 0 {
		typeDefinition.Metadata.Relations[RelationParent] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: getResourceParentRelatedTypes(resourceNode.ParentResources),
		}
		typeDefinition.Relations[RelationParent] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{},
		}
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)

		permChildren := []*openfgav1.Userset{
			{Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}}},
		}

		if len(resourceNode.ParentResources) > 0 {
			permChildren = append(permChildren, &openfgav1.Userset{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset: &openfgav1.ObjectRelation{
							Relation: RelationParent,
						},
						ComputedUserset: &openfgav1.ObjectRelation{
							Relation: hashedPermission,
						},
					},
				},
			})
		}

		typeDefinition.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				{Type: TypeInternalUser},
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}

		if len(permChildren) == 1 {
			typeDefinition.Relations[hashedPermission] = permChildren[0]
		} else {
			typeDefinition.Relations[hashedPermission] = &openfgav1.Userset{
				Userset: &openfgav1.Userset_Union{
					Union: &openfgav1.Usersets{
						Child: permChildren,
					},
				},
			}
		}
	}

	return typeDefinition
}

func getMinimalAuthorizationModel() *openfgav1.AuthorizationModel {
	return &openfgav1.AuthorizationModel{
		SchemaVersion: "1.2",
		TypeDefinitions: []*openfgav1.TypeDefinition{
			getUserTypeDefinition(),
			getUserGroupTypeDefinition(),
		},
	}
}

func getUserTypeDefinition() *openfgav1.TypeDefinition {
	return &openfgav1.TypeDefinition{
		Type: TypeInternalUser,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{},
	}
}

func getUserGroupTypeDefinition() *openfgav1.TypeDefinition {
	return &openfgav1.TypeDefinition{
		Type: TypeInternalUserGroup,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationMember: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{
							Type: TypeInternalUser,
						},
					},
				},
				RelationAssignee: {
					DirectlyRelatedUserTypes: nil,
				},
			},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationMember: {
				Userset: &openfgav1.Userset_This{
					This: &openfgav1.DirectUserset{},
				},
			},
			RelationAssignee: {
				Userset: &openfgav1.Userset_ComputedUserset{
					ComputedUserset: &openfgav1.ObjectRelation{
						Relation: RelationMember,
					},
				},
			},
		},
	}
}

// getRootTypeDefinition builds the OpenFGA TypeDefinition for the
// iam.miloapis.com/Root type for the authorization model.
//
// ResourceKind PolicyBindings write tuples of the form:
//
//	(InternalUser:<uid>, hash(svc/resource.verb), iam.miloapis.com/Root:<apiGroup>/<Kind>)
//
// The Root type therefore needs the same hashed-permission relations that
// individual resource types carry, so that Check calls against Root objects
// resolve correctly.
func getRootTypeDefinition(permissions []string) *openfgav1.TypeDefinition {
	root := &openfgav1.TypeDefinition{
		Type: TypeRoot,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{},
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)
		root.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				{Type: TypeInternalUser},
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}
		root.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}},
		}
	}

	return root
}

func hashPermission(permission string) string {
	hasher := fnv.New32a()
	//revive:disable-next-line:unhandled-error a
	hasher.Write([]byte(permission))

	return hex.EncodeToString(hasher.Sum(nil))
}

// HashPermission is the exported version of hashPermission for use by the webhook.
func HashPermission(permission string) string {
	return hashPermission(permission)
}

// calculateHierarchicalPermissions calculates which permissions each resource type should have
// based on its position in the hierarchy. Each resource gets its own permissions plus
// all permissions from its descendants (children, grandchildren, etc.)
func calculateHierarchicalPermissions(rootNode *resourceGraphNode) map[string][]string {
	hierarchicalPermissions := make(map[string][]string)
	calculatePermissionsForNode(rootNode, hierarchicalPermissions)
	return hierarchicalPermissions
}

// calculatePermissionsForNode recursively calculates permissions for a node and all its descendants
func calculatePermissionsForNode(node *resourceGraphNode, permissionsMap map[string][]string) []string {
	if node == nil {
		return []string{}
	}

	if node.ResourceType == TypeRoot {
		for _, child := range node.ChildResources {
			calculatePermissionsForNode(child, permissionsMap)
		}
		return []string{}
	}

	if permissions, exists := permissionsMap[node.ResourceType]; exists {
		return permissions
	}

	nodePermissions := make([]string, len(node.DirectPermissions))
	copy(nodePermissions, node.DirectPermissions)

	for _, child := range node.ChildResources {
		childPermissions := calculatePermissionsForNode(child, permissionsMap)
		nodePermissions = append(nodePermissions, childPermissions...)
	}

	nodePermissions = removeDuplicatePermissions(nodePermissions)
	sort.Strings(nodePermissions)
	permissionsMap[node.ResourceType] = nodePermissions

	return nodePermissions
}

// removeDuplicatePermissions removes duplicate permission strings from a slice
func removeDuplicatePermissions(permissions []string) []string {
	seen := make(map[string]bool)
	result := []string{}

	for _, permission := range permissions {
		if !seen[permission] {
			seen[permission] = true
			result = append(result, permission)
		}
	}

	return result
}

// getResourceTypeDefinitionsWithHierarchicalPermissions creates type definitions with
// permissions assigned based on hierarchical relationships
func getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions map[string][]string, node *resourceGraphNode) map[string]*openfgav1.TypeDefinition {
	types := map[string]*openfgav1.TypeDefinition{}

	if node.ResourceType != TypeRoot {
		permissions := hierarchicalPermissions[node.ResourceType]
		if permissions == nil {
			permissions = []string{}
		}
		types[node.ResourceType] = getResourceTypeDefinition(permissions, node)
	}

	for _, child := range node.ChildResources {
		childTypes := getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, child)
		for k, v := range childTypes {
			types[k] = v
		}
	}

	return types
}
