package openfga

import (
	"context"
	"encoding/hex"
	"fmt"
	"hash/fnv"
	"sort"
	"strings"

	"github.com/google/go-cmp/cmp"
	openfgav1 "github.com/openfga/api/proto/openfga/v1"
	"go.miloapis.com/auth-provider-openfga/internal/features"
	iamdatumapiscomv1alpha1 "go.miloapis.com/milo/pkg/apis/iam/v1alpha1"
	"google.golang.org/protobuf/testing/protocmp"
	"google.golang.org/protobuf/types/known/wrapperspb"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	utilfeature "k8s.io/apiserver/pkg/util/feature"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	// AuthorizationModelConfigMapName is the name of the ConfigMap that holds
	// AuthorizationModelConfigMapName is the default name for the ConfigMap
	// that holds the latest authorization model ID. Used as the flag default.
	AuthorizationModelConfigMapName = "openfga-authorization-model"

	// AuthorizationModelIDKey is the key within the ConfigMap's data map that
	// stores the model ID string.
	AuthorizationModelIDKey = "model-id"
)

type AuthorizationModelReconciler struct {
	StoreID string
	OpenFGA openfgav1.OpenFGAServiceClient

	// K8sClient is used to create/update the ConfigMap that holds the current
	// authorization model ID. When nil, the ConfigMap write is skipped.
	K8sClient client.Client
	// Namespace is the Kubernetes namespace in which the ConfigMap is created.
	Namespace string
	// ConfigMapName is the name of the ConfigMap that stores the model ID.
	// Defaults to DefaultAuthorizationModelConfigMapName if empty.
	ConfigMapName string
}

// getAuthorizationModelComparisonOptions returns the standardized cmp.Option slice for comparing authorization models
// with options to ignore ordering differences and the OpenFGA-assigned id field
func getAuthorizationModelComparisonOptions() []cmp.Option {
	return []cmp.Option{
		// Use protocmp.Transform for proper protobuf message comparison
		protocmp.Transform(),
		// Ignore the id field since it's assigned by OpenFGA and not semantically meaningful
		protocmp.IgnoreFields(&openfgav1.AuthorizationModel{}, "id"),
		// Sort repeated fields that can have different orderings without changing semantics
		protocmp.SortRepeated(func(a, b *openfgav1.TypeDefinition) bool {
			return a.Type < b.Type
		}),
		protocmp.SortRepeated(func(a, b *openfgav1.RelationReference) bool {
			return a.Type < b.Type
		}),
	}
}

// authorizationModelsEqual compares two authorization models using go-cmp with protocmp
// and options to ignore ordering differences that don't affect semantics
func authorizationModelsEqual(current, merged *openfgav1.AuthorizationModel) bool {
	if current == nil && merged == nil {
		return true
	}
	if current == nil || merged == nil {
		return false
	}

	return cmp.Equal(current, merged, getAuthorizationModelComparisonOptions()...)
}

func (r *AuthorizationModelReconciler) ReconcileAuthorizationModel(ctx context.Context, protectedResources []iamdatumapiscomv1alpha1.ProtectedResource) error {
	log := logf.FromContext(ctx).WithValues("component", "AuthorizationModelReconciler")

	currentAuthorizationModel, err := r.getCurrentAuthorizationModel(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current authorization model: %w", err)
	}

	newAuthorizationModel, err := r.createExpectedAuthorizationModel(protectedResources)
	if err != nil {
		return fmt.Errorf("failed to create new authorization model: %w", err)
	}

	mergedAuthorizationModel := &openfgav1.AuthorizationModel{
		SchemaVersion: newAuthorizationModel.SchemaVersion,
		// Conditions are not dynamically generated by the IAM system so we can
		// safely set the conditions to whatever is already in the authorization
		// model.
		//
		// TODO: Update when conditions are dynamically created by the IAM system.
		Conditions: currentAuthorizationModel.Conditions,
	}

	// Create a map to track existing types and prevent duplicates.
	// Under the direct-permission model the IAM system manages InternalUser and
	// InternalUserGroup only. All other types (InternalRole, RoleBinding, Root)
	// are no longer generated.
	existingTypes := make(map[string]bool)

	iamSystemTypes := map[string]bool{
		TypeInternalUser:      true,
		TypeInternalUserGroup: true,
		// Legacy types that are now managed (and regenerated) by this reconciler
		// so that stale definitions from previous model versions are replaced.
		TypeInternalRole: true,
		TypeRoleBinding:  true,
		TypeRoot:         true,
	}

	// Go through the existing type definitions and add any that were provided
	// through the OpenFGA schema language, excluding IAM system managed types.
	for _, typeDefinition := range currentAuthorizationModel.TypeDefinitions {
		// Skip IAM system managed types as they will be regenerated
		if iamSystemTypes[typeDefinition.Type] {
			continue
		}

		// The type definitions added by the IAM system will always be in the
		// format `{service_name}/{resource_type}`. Since this format is only
		// valid when building the resource model in JSON, we can safely
		// guarantee that type definitions added by Datum OS through the OpenFGA
		// schema language will never contain a "/" character.
		if len(strings.Split(typeDefinition.Type, "/")) == 1 {
			mergedAuthorizationModel.TypeDefinitions = append(mergedAuthorizationModel.TypeDefinitions, typeDefinition)
			existingTypes[typeDefinition.Type] = true
		}
	}

	// Add new type definitions, but only if they don't already exist
	for _, typeDefinition := range newAuthorizationModel.TypeDefinitions {
		if !existingTypes[typeDefinition.Type] {
			mergedAuthorizationModel.TypeDefinitions = append(mergedAuthorizationModel.TypeDefinitions, typeDefinition)
			existingTypes[typeDefinition.Type] = true
		}
	}

	// Compare using go-cmp with protocmp for proper protobuf comparison
	if authorizationModelsEqual(currentAuthorizationModel, mergedAuthorizationModel) {
		log.Info("Authorization model is already up to date, skipping write operation")
		// Even when the model is unchanged we still want the ConfigMap to
		// reflect the current model ID (e.g. after a controller restart or
		// a fresh cluster where the ConfigMap was never created).
		if r.K8sClient != nil && r.Namespace != "" && currentAuthorizationModel.GetId() != "" {
			if cmErr := r.writeModelIDToConfigMap(ctx, currentAuthorizationModel.GetId()); cmErr != nil {
				log.Error(cmErr, "failed to write authorization model ID to ConfigMap (no-op path)",
					"model_id", currentAuthorizationModel.GetId())
			}
		}
		return nil
	}

	log.Info("Authorization model has changed, updating OpenFGA store",
		"currentTypeCount", len(currentAuthorizationModel.TypeDefinitions),
		"mergedTypeCount", len(mergedAuthorizationModel.TypeDefinitions))

	// Add debugging diff output to understand what's different
	if diff := cmp.Diff(currentAuthorizationModel, mergedAuthorizationModel, getAuthorizationModelComparisonOptions()...); diff != "" {
		log.Info("Authorization model diff detected", "diff", diff)
	}

	writeResp, err := r.OpenFGA.WriteAuthorizationModel(ctx, &openfgav1.WriteAuthorizationModelRequest{
		StoreId:         r.StoreID,
		SchemaVersion:   mergedAuthorizationModel.SchemaVersion,
		TypeDefinitions: mergedAuthorizationModel.TypeDefinitions,
		Conditions:      mergedAuthorizationModel.Conditions,
	})
	if err != nil {
		return fmt.Errorf("failed to reconcile authorization model: %w", err)
	}

	if r.K8sClient != nil && r.Namespace != "" && writeResp.GetAuthorizationModelId() != "" {
		if cmErr := r.writeModelIDToConfigMap(ctx, writeResp.GetAuthorizationModelId()); cmErr != nil {
			// Log the error but do not fail the reconciliation — the webhook
			// can still resolve the latest model dynamically.
			log.Error(cmErr, "failed to write authorization model ID to ConfigMap",
				"model_id", writeResp.GetAuthorizationModelId())
		}
	}

	return nil
}

// writeModelIDToConfigMap creates or updates the openfga-authorization-model
// ConfigMap in the configured namespace with the given model ID.
func (r *AuthorizationModelReconciler) writeModelIDToConfigMap(ctx context.Context, modelID string) error {
	cmName := r.ConfigMapName

	log := logf.FromContext(ctx).WithValues("component", "AuthorizationModelReconciler", "model_id", modelID)

	cm := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      cmName,
			Namespace: r.Namespace,
		},
	}

	result, err := controllerutil.CreateOrUpdate(ctx, r.K8sClient, cm, func() error {
		if cm.Data == nil {
			cm.Data = make(map[string]string)
		}
		cm.Data[AuthorizationModelIDKey] = modelID
		return nil
	})
	if err != nil {
		return fmt.Errorf("failed to create/update authorization model ConfigMap: %w", err)
	}

	log.Info("authorization model ID written to ConfigMap",
		"configmap", cmName,
		"namespace", r.Namespace,
		"result", result,
	)
	return nil
}

func (r *AuthorizationModelReconciler) getCurrentAuthorizationModel(ctx context.Context) (*openfgav1.AuthorizationModel, error) {
	models, err := r.OpenFGA.ReadAuthorizationModels(ctx, &openfgav1.ReadAuthorizationModelsRequest{
		StoreId: r.StoreID,
		// Only request the first result because it'll always be the latest
		// authorization model that was created for the store.
		PageSize: wrapperspb.Int32(1),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list authorization models: %w", err)
	}

	if len(models.AuthorizationModels) == 0 {
		// No authorization model has been created yet so we'll just return an
		// empty model.
		return &openfgav1.AuthorizationModel{}, nil
	}

	// Retrieve the full authorization model definition
	resp, err := r.OpenFGA.ReadAuthorizationModel(ctx, &openfgav1.ReadAuthorizationModelRequest{
		StoreId: r.StoreID,
		Id:      models.AuthorizationModels[0].Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get authorization model: %w", err)
	}

	return resp.AuthorizationModel, nil
}

func (r *AuthorizationModelReconciler) createExpectedAuthorizationModel(protectedResources []iamdatumapiscomv1alpha1.ProtectedResource) (*openfgav1.AuthorizationModel, error) {
	directEnabled := utilfeature.DefaultFeatureGate.Enabled(features.DirectPermissionTuples)
	legacyEnabled := utilfeature.DefaultFeatureGate.Enabled(features.LegacyRoleBindingModel)

	// If no ProtectedResources exist, return a minimal authorization model
	if len(protectedResources) == 0 {
		return getMinimalAuthorizationModel(), nil
	}

	// Build the resource hierarchy — needed by both models.
	resourceGraph, err := getResourceGraph(protectedResources)
	if err != nil {
		return nil, fmt.Errorf("failed to get resource graph: %v", err)
	}

	// Calculate hierarchical permissions for each resource type
	hierarchicalPermissions := calculateHierarchicalPermissions(resourceGraph)

	// Collect all unique permissions (used by both Root type variants and by
	// the legacy InternalRole/RoleBinding types).
	allPermsSet := make(map[string]struct{})
	for _, perms := range hierarchicalPermissions {
		for _, p := range perms {
			allPermsSet[p] = struct{}{}
		}
	}
	allPermissions := make([]string, 0, len(allPermsSet))
	for p := range allPermsSet {
		allPermissions = append(allPermissions, p)
	}
	sort.Strings(allPermissions)

	// InternalUser and InternalUserGroup are shared by both models.
	typeDefinitions := []*openfgav1.TypeDefinition{
		getUserTypeDefinition(),
		getUserGroupTypeDefinition(),
	}

	switch {
	case directEnabled && legacyEnabled:
		// Hybrid mode: each resource type carries relations from BOTH models.
		// Hashed permission relations accept direct user/group writes (This)
		// AND resolve through legacy rolebinding/rootbinding tupleset lookups.
		// This allows the controller to dual-write both tuple formats while
		// the webhook continues using the legacy check path.
		resourceTypeDefinitions := getHybridResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, resourceGraph)

		sortedResourceTypes := make([]string, 0, len(resourceTypeDefinitions))
		for resourceType := range resourceTypeDefinitions {
			sortedResourceTypes = append(sortedResourceTypes, resourceType)
		}
		sort.Strings(sortedResourceTypes)

		for _, resourceType := range sortedResourceTypes {
			typeDefinitions = append(typeDefinitions, resourceTypeDefinitions[resourceType])
		}

		// Include the legacy infrastructure types (InternalRole, RoleBinding)
		// and a hybrid Root type that accepts both direct and legacy tuples.
		typeDefinitions = append(typeDefinitions,
			getLegacyInternalRoleTypeDefinition(allPermissions),
			getLegacyRoleBindingTypeDefinition(allPermissions),
		)
		resourceTypes := getAllResourceTypes(resourceGraph)
		typeDefinitions = append(typeDefinitions, getHybridRootTypeDefinition(allPermissions, resourceTypes))

	case directEnabled:
		// Direct-permission model only: resource types with direct user/group
		// relations and a simplified Root type.
		resourceTypeDefinitions := getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, resourceGraph)

		sortedResourceTypes := make([]string, 0, len(resourceTypeDefinitions))
		for resourceType := range resourceTypeDefinitions {
			sortedResourceTypes = append(sortedResourceTypes, resourceType)
		}
		sort.Strings(sortedResourceTypes)

		for _, resourceType := range sortedResourceTypes {
			typeDefinitions = append(typeDefinitions, resourceTypeDefinitions[resourceType])
		}

		typeDefinitions = append(typeDefinitions, getRootTypeDefinition(allPermissions))

	case legacyEnabled:
		// Legacy RoleBinding model only: InternalRole + RoleBinding types
		// plus legacy resource types (rolebinding/rootbinding relations).
		resourceTypeDefinitions := getLegacyResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, resourceGraph)

		sortedResourceTypes := make([]string, 0, len(resourceTypeDefinitions))
		for resourceType := range resourceTypeDefinitions {
			sortedResourceTypes = append(sortedResourceTypes, resourceType)
		}
		sort.Strings(sortedResourceTypes)

		for _, resourceType := range sortedResourceTypes {
			typeDefinitions = append(typeDefinitions, resourceTypeDefinitions[resourceType])
		}

		typeDefinitions = append(typeDefinitions,
			getLegacyInternalRoleTypeDefinition(allPermissions),
			getLegacyRoleBindingTypeDefinition(allPermissions),
		)
		resourceTypes := getAllResourceTypes(resourceGraph)
		typeDefinitions = append(typeDefinitions, getLegacyRootTypeDefinition(allPermissions, resourceTypes))
	}

	return &openfgav1.AuthorizationModel{
		SchemaVersion:   "1.2",
		TypeDefinitions: typeDefinitions,
	}, nil
}

// getAllResourceTypes collects all resource type strings from the resource graph.
func getAllResourceTypes(node *resourceGraphNode) []string {
	if node == nil {
		return nil
	}
	var types []string
	if node.ResourceType != TypeRoot {
		types = append(types, node.ResourceType)
	}
	for _, child := range node.ChildResources {
		types = append(types, getAllResourceTypes(child)...)
	}
	return removeDuplicateStrings(types)
}

// removeDuplicateStrings returns a deduplicated copy of the input slice.
func removeDuplicateStrings(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if _, ok := seen[s]; !ok {
			seen[s] = struct{}{}
			out = append(out, s)
		}
	}
	return out
}

func getResourceParentRelatedTypes(parents []string) (relations []*openfgav1.RelationReference) {
	for _, parent := range parents {
		relations = append(relations, &openfgav1.RelationReference{
			Type: parent,
		})
	}
	return
}

// getResourceTypeDefinition builds the OpenFGA TypeDefinition for a resource
// under the direct-permission model.
//
// Each hashed-permission relation accepts:
//   - A directly-assigned InternalUser
//   - A directly-assigned InternalUserGroup (resolved via its "member" relation)
//   - Permissions inherited from the parent resource (via the "parent" tupleset)
//
// This replaces the previous RoleBinding/InternalRole intersection that
// required ~27 datastore reads per Check. With direct tuples a Check resolves
// in 1-3 reads.
func getResourceTypeDefinition(permissions []string, resourceNode *resourceGraphNode) *openfgav1.TypeDefinition {
	typeDefinition := &openfgav1.TypeDefinition{
		Type: resourceNode.ResourceType,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: strings.Split(resourceNode.ResourceType, "/")[0],
		},
		Relations: map[string]*openfgav1.Userset{},
	}

	// Only create a parent reference if the resource has parent relationships.
	if len(resourceNode.ParentResources) > 0 {
		typeDefinition.Metadata.Relations[RelationParent] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: getResourceParentRelatedTypes(resourceNode.ParentResources),
		}
		typeDefinition.Relations[RelationParent] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{},
		}
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)

		// Build the union of assignment sources for this permission relation.
		// Start with direct user/group assignment (This).
		permChildren := []*openfgav1.Userset{
			// Direct assignment: an InternalUser or InternalUserGroup#member tuple
			// grants this permission on the resource directly.
			{Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}}},
		}

		// If the resource has parents, add permission inheritance from the parent.
		if len(resourceNode.ParentResources) > 0 {
			permChildren = append(permChildren, &openfgav1.Userset{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset: &openfgav1.ObjectRelation{
							Relation: RelationParent,
						},
						ComputedUserset: &openfgav1.ObjectRelation{
							Relation: hashedPermission,
						},
					},
				},
			})
		}

		// The relation metadata declares which user types may be directly assigned.
		typeDefinition.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				// Individual users
				{Type: TypeInternalUser},
				// Group members (resolved transitively via InternalUserGroup#member)
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}

		if len(permChildren) == 1 {
			// No parent: just use This directly (avoids unnecessary Union wrapper).
			typeDefinition.Relations[hashedPermission] = permChildren[0]
		} else {
			typeDefinition.Relations[hashedPermission] = &openfgav1.Userset{
				Userset: &openfgav1.Userset_Union{
					Union: &openfgav1.Usersets{
						Child: permChildren,
					},
				},
			}
		}
	}

	return typeDefinition
}

func getMinimalAuthorizationModel() *openfgav1.AuthorizationModel {
	// Return a minimal authorization model with just InternalUser and
	// InternalUserGroup when no ProtectedResources exist.
	return &openfgav1.AuthorizationModel{
		SchemaVersion: "1.2",
		TypeDefinitions: []*openfgav1.TypeDefinition{
			getUserTypeDefinition(),
			getUserGroupTypeDefinition(),
		},
	}
}

func getUserTypeDefinition() *openfgav1.TypeDefinition {
	return &openfgav1.TypeDefinition{
		Type: TypeInternalUser,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{},
	}
}

func getUserGroupTypeDefinition() *openfgav1.TypeDefinition {
	return &openfgav1.TypeDefinition{
		Type: TypeInternalUserGroup,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationMember: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{
							Type: TypeInternalUser,
						},
					},
				},
				RelationAssignee: {
					DirectlyRelatedUserTypes: nil,
				},
			},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationMember: {
				Userset: &openfgav1.Userset_This{
					This: &openfgav1.DirectUserset{},
				},
			},
			RelationAssignee: {
				Userset: &openfgav1.Userset_ComputedUserset{
					ComputedUserset: &openfgav1.ObjectRelation{
						Relation: RelationMember,
					},
				},
			},
		},
	}
}

// getRootTypeDefinition builds the OpenFGA TypeDefinition for the
// iam.miloapis.com/Root type under the direct-permission model.
//
// ResourceKind PolicyBindings write tuples of the form:
//
//	(InternalUser:<uid>, hash(svc/resource.verb), iam.miloapis.com/Root:<apiGroup>/<Kind>)
//
// The Root type therefore needs the same hashed-permission relations that
// individual resource types carry, so that Check calls against Root objects
// resolve correctly.
func getRootTypeDefinition(permissions []string) *openfgav1.TypeDefinition {
	root := &openfgav1.TypeDefinition{
		Type: TypeRoot,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{},
			SourceInfo: &openfgav1.SourceInfo{
				File: SourceFile,
			},
			Module: Module,
		},
		Relations: map[string]*openfgav1.Userset{},
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)
		root.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				{Type: TypeInternalUser},
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}
		root.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}},
		}
	}

	return root
}

func hashPermission(permission string) string {
	hasher := fnv.New32a()
	//revive:disable-next-line:unhandled-error a
	hasher.Write([]byte(permission))

	return hex.EncodeToString(hasher.Sum(nil))
}

func HashPermission(permission string) string {
	return hashPermission(permission)
}

// calculateHierarchicalPermissions calculates which permissions each resource type should have
// based on its position in the hierarchy. Each resource gets its own permissions plus
// all permissions from its descendants (children, grandchildren, etc.)
//
// Root-level resources (direct children of the Root node that have no parent
// resources) receive ALL permissions from the entire graph. This is required
// because the authorization webhook may scope checks to these resource types
// (e.g. checking projects.list against a User object in a user control plane),
// and the permission must exist as a relation on the type for the check to
// succeed.
func calculateHierarchicalPermissions(rootNode *resourceGraphNode) map[string][]string {
	hierarchicalPermissions := make(map[string][]string)

	// Traverse the entire graph and calculate permissions for each node
	calculatePermissionsForNode(rootNode, hierarchicalPermissions)

	// Collect ALL permissions across every resource type.
	allPermsSet := make(map[string]struct{})
	for _, perms := range hierarchicalPermissions {
		for _, p := range perms {
			allPermsSet[p] = struct{}{}
		}
	}
	allPerms := make([]string, 0, len(allPermsSet))
	for p := range allPermsSet {
		allPerms = append(allPerms, p)
	}

	// Root-level resources (no parentResources) must carry all permissions.
	for _, child := range rootNode.ChildResources {
		if len(child.ParentResources) == 0 {
			hierarchicalPermissions[child.ResourceType] = removeDuplicatePermissions(allPerms)
		}
	}

	return hierarchicalPermissions
}

// calculatePermissionsForNode recursively calculates permissions for a node and all its descendants
func calculatePermissionsForNode(node *resourceGraphNode, permissionsMap map[string][]string) []string {
	if node == nil {
		return []string{}
	}

	// Skip the root IAM node as it's handled separately
	if node.ResourceType == TypeRoot {
		// Process children but don't assign permissions to the IAM root
		for _, child := range node.ChildResources {
			calculatePermissionsForNode(child, permissionsMap)
		}
		return []string{}
	}

	// If we've already calculated permissions for this node, return them
	if permissions, exists := permissionsMap[node.ResourceType]; exists {
		return permissions
	}

	// Start with this node's direct permissions
	nodePermissions := make([]string, len(node.DirectPermissions))
	copy(nodePermissions, node.DirectPermissions)

	// Add permissions from all child resources
	for _, child := range node.ChildResources {
		childPermissions := calculatePermissionsForNode(child, permissionsMap)
		nodePermissions = append(nodePermissions, childPermissions...)
	}

	// Remove duplicates
	nodePermissions = removeDuplicatePermissions(nodePermissions)

	// Store the calculated permissions
	permissionsMap[node.ResourceType] = nodePermissions

	return nodePermissions
}

// removeDuplicatePermissions removes duplicate permission strings from a slice
func removeDuplicatePermissions(permissions []string) []string {
	seen := make(map[string]bool)
	result := []string{}

	for _, permission := range permissions {
		if !seen[permission] {
			seen[permission] = true
			result = append(result, permission)
		}
	}

	return result
}

// getResourceTypeDefinitionsWithHierarchicalPermissions creates type definitions with
// permissions assigned based on hierarchical relationships
func getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions map[string][]string, node *resourceGraphNode) map[string]*openfgav1.TypeDefinition {
	types := map[string]*openfgav1.TypeDefinition{}

	// Process the current node
	if node.ResourceType != TypeRoot {
		permissions := hierarchicalPermissions[node.ResourceType]
		if permissions == nil {
			permissions = []string{} // Default to empty if not found
		}
		types[node.ResourceType] = getResourceTypeDefinition(permissions, node)
	}

	// Process all child nodes
	for _, child := range node.ChildResources {
		childTypes := getResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, child)
		for k, v := range childTypes {
			types[k] = v
		}
	}

	return types
}

// =============================================================================
// Legacy RoleBinding model type definitions
// These are only included when the LegacyRoleBindingModel feature gate is
// enabled. They replicate the type shapes from before the direct-permission
// migration.
// =============================================================================

// getLegacyInternalRoleTypeDefinition returns the InternalRole type used by the
// legacy RoleBinding intersection model.
func getLegacyInternalRoleTypeDefinition(permissions []string) *openfgav1.TypeDefinition {
	sortedPermissions := make([]string, len(permissions))
	copy(sortedPermissions, permissions)
	sort.Strings(sortedPermissions)

	role := &openfgav1.TypeDefinition{
		Type: TypeInternalRole,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationAssignee: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeInternalUser},
					},
				},
			},
			SourceInfo: &openfgav1.SourceInfo{File: SourceFile},
			Module:     Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationAssignee: {
				Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}},
			},
		},
	}

	for _, permission := range sortedPermissions {
		hashedPermission := hashPermission(permission)
		role.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				{
					Type:               TypeInternalUser,
					RelationOrWildcard: &openfgav1.RelationReference_Wildcard{},
				},
			},
		}
		role.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}},
		}
	}

	return role
}

// getLegacyRoleBindingTypeDefinition returns the RoleBinding type used by the
// legacy intersection model.
func getLegacyRoleBindingTypeDefinition(permissions []string) *openfgav1.TypeDefinition {
	sortedPermissions := make([]string, len(permissions))
	copy(sortedPermissions, permissions)
	sort.Strings(sortedPermissions)

	roleBinding := &openfgav1.TypeDefinition{
		Type: TypeRoleBinding,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationInternalRole: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeInternalRole},
					},
				},
				RelationInternalUser: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeInternalUser},
						{
							Type:               TypeInternalUser,
							RelationOrWildcard: &openfgav1.RelationReference_Wildcard{},
						},
						{
							Type: TypeInternalUserGroup,
							RelationOrWildcard: &openfgav1.RelationReference_Relation{
								Relation: RelationAssignee,
							},
						},
					},
				},
			},
			SourceInfo: &openfgav1.SourceInfo{File: SourceFile},
			Module:     Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationInternalRole: {
				Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}},
			},
			RelationInternalUser: {
				Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}},
			},
		},
	}

	for _, permission := range sortedPermissions {
		hashedPermission := hashPermission(permission)
		roleBinding.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_Intersection{
				Intersection: &openfgav1.Usersets{
					Child: []*openfgav1.Userset{
						{
							Userset: &openfgav1.Userset_ComputedUserset{
								ComputedUserset: &openfgav1.ObjectRelation{
									Relation: RelationInternalUser,
								},
							},
						},
						{
							Userset: &openfgav1.Userset_TupleToUserset{
								TupleToUserset: &openfgav1.TupleToUserset{
									Tupleset: &openfgav1.ObjectRelation{
										Relation: RelationInternalRole,
									},
									ComputedUserset: &openfgav1.ObjectRelation{
										Relation: hashedPermission,
									},
								},
							},
						},
					},
				},
			},
		}
	}

	return roleBinding
}

// getLegacyResourceTypeDefinition builds the OpenFGA TypeDefinition for a
// resource under the legacy RoleBinding model. Relations are resolved through
// rolebinding and rootbinding tupleset lookups instead of direct user/group
// assignment.
func getLegacyResourceTypeDefinition(permissions []string, resourceNode *resourceGraphNode) *openfgav1.TypeDefinition {
	typeDefinition := &openfgav1.TypeDefinition{
		Type: resourceNode.ResourceType,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationRoleBinding: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeRoleBinding},
					},
				},
				RelationRootBinding: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeRoot},
					},
				},
			},
			SourceInfo: &openfgav1.SourceInfo{File: SourceFile},
			Module:     strings.Split(resourceNode.ResourceType, "/")[0],
		},
		Relations: map[string]*openfgav1.Userset{
			RelationRoleBinding: {Userset: &openfgav1.Userset_This{}},
			RelationRootBinding: {Userset: &openfgav1.Userset_This{}},
		},
	}

	if len(resourceNode.ParentResources) > 0 {
		typeDefinition.Metadata.Relations[RelationParent] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: getResourceParentRelatedTypes(resourceNode.ParentResources),
		}
		typeDefinition.Relations[RelationParent] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{},
		}
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)

		permChildren := []*openfgav1.Userset{
			{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset:        &openfgav1.ObjectRelation{Relation: RelationRoleBinding},
						ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
					},
				},
			},
			{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset:        &openfgav1.ObjectRelation{Relation: RelationRootBinding},
						ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
					},
				},
			},
		}

		if len(resourceNode.ParentResources) > 0 {
			permChildren = append(permChildren, &openfgav1.Userset{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset:        &openfgav1.ObjectRelation{Relation: RelationParent},
						ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
					},
				},
			})
		}

		typeDefinition.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_Union{
				Union: &openfgav1.Usersets{Child: permChildren},
			},
		}
	}

	return typeDefinition
}

// getLegacyResourceTypeDefinitionsWithHierarchicalPermissions walks the
// resource graph and returns legacy-model TypeDefinitions for each resource.
func getLegacyResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions map[string][]string, node *resourceGraphNode) map[string]*openfgav1.TypeDefinition {
	types := map[string]*openfgav1.TypeDefinition{}

	if node.ResourceType != TypeRoot {
		permissions := hierarchicalPermissions[node.ResourceType]
		if permissions == nil {
			permissions = []string{}
		}
		types[node.ResourceType] = getLegacyResourceTypeDefinition(permissions, node)
	}

	for _, child := range node.ChildResources {
		childTypes := getLegacyResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, child)
		for k, v := range childTypes {
			types[k] = v
		}
	}

	return types
}

// getLegacyRootTypeDefinition builds the Root type for the legacy RoleBinding
// model. Permissions on Root objects are resolved through the rolebinding
// tupleset rather than being stored as direct tuples.
func getLegacyRootTypeDefinition(permissions []string, resourceTypes []string) *openfgav1.TypeDefinition {
	sortedPermissions := make([]string, len(permissions))
	copy(sortedPermissions, permissions)
	sort.Strings(sortedPermissions)

	sortedResourceTypes := make([]string, len(resourceTypes))
	copy(sortedResourceTypes, resourceTypes)
	sort.Strings(sortedResourceTypes)

	relationReferences := make([]*openfgav1.RelationReference, 0, len(sortedResourceTypes))
	for _, rt := range sortedResourceTypes {
		relationReferences = append(relationReferences, &openfgav1.RelationReference{Type: rt})
	}

	root := &openfgav1.TypeDefinition{
		Type: TypeRoot,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationRoleBinding: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeRoleBinding},
					},
				},
				RelationRootBinding: {
					DirectlyRelatedUserTypes: relationReferences,
				},
			},
			SourceInfo: &openfgav1.SourceInfo{File: SourceFile},
			Module:     Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationRoleBinding: {Userset: &openfgav1.Userset_This{}},
			RelationRootBinding: {Userset: &openfgav1.Userset_This{}},
		},
	}

	for _, permission := range sortedPermissions {
		hashedPermission := hashPermission(permission)
		root.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_TupleToUserset{
				TupleToUserset: &openfgav1.TupleToUserset{
					Tupleset:        &openfgav1.ObjectRelation{Relation: RelationRoleBinding},
					ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
				},
			},
		}
	}

	return root
}

// =============================================================================
// Hybrid model type definitions (dual-write migration)
// These combine both direct user/group assignment (This) and legacy
// rolebinding/rootbinding tupleset resolution in a single type definition,
// allowing both tuple formats to coexist.
// =============================================================================

// getHybridResourceTypeDefinition builds a resource type that supports both
// direct tuple writes and legacy check resolution. Each hashed permission
// relation is a union of:
//   - This (direct InternalUser / InternalUserGroup#member assignment)
//   - TupleToUserset(rolebinding, hash(perm))  — legacy check path
//   - TupleToUserset(rootbinding, hash(perm))  — legacy check path
//   - TupleToUserset(parent, hash(perm))       — hierarchical inheritance
func getHybridResourceTypeDefinition(permissions []string, resourceNode *resourceGraphNode) *openfgav1.TypeDefinition {
	typeDefinition := &openfgav1.TypeDefinition{
		Type: resourceNode.ResourceType,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationRoleBinding: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeRoleBinding},
					},
				},
				RelationRootBinding: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeRoot},
					},
				},
			},
			SourceInfo: &openfgav1.SourceInfo{File: SourceFile},
			Module:     strings.Split(resourceNode.ResourceType, "/")[0],
		},
		Relations: map[string]*openfgav1.Userset{
			RelationRoleBinding: {Userset: &openfgav1.Userset_This{}},
			RelationRootBinding: {Userset: &openfgav1.Userset_This{}},
		},
	}

	if len(resourceNode.ParentResources) > 0 {
		typeDefinition.Metadata.Relations[RelationParent] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: getResourceParentRelatedTypes(resourceNode.ParentResources),
		}
		typeDefinition.Relations[RelationParent] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_This{},
		}
	}

	for _, permission := range permissions {
		hashedPermission := hashPermission(permission)

		// Metadata declares which user types may be directly assigned
		// (needed for the direct-permission tuple writes).
		typeDefinition.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				{Type: TypeInternalUser},
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}

		permChildren := []*openfgav1.Userset{
			// Direct assignment (new model)
			{Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}}},
			// Legacy: resolve through RoleBinding chain
			{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset:        &openfgav1.ObjectRelation{Relation: RelationRoleBinding},
						ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
					},
				},
			},
			// Legacy: resolve through RootBinding chain
			{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset:        &openfgav1.ObjectRelation{Relation: RelationRootBinding},
						ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
					},
				},
			},
		}

		// Hierarchical inheritance from parent
		if len(resourceNode.ParentResources) > 0 {
			permChildren = append(permChildren, &openfgav1.Userset{
				Userset: &openfgav1.Userset_TupleToUserset{
					TupleToUserset: &openfgav1.TupleToUserset{
						Tupleset:        &openfgav1.ObjectRelation{Relation: RelationParent},
						ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
					},
				},
			})
		}

		typeDefinition.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_Union{
				Union: &openfgav1.Usersets{Child: permChildren},
			},
		}
	}

	return typeDefinition
}

// getHybridResourceTypeDefinitionsWithHierarchicalPermissions walks the
// resource graph and returns hybrid-model TypeDefinitions for each resource.
func getHybridResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions map[string][]string, node *resourceGraphNode) map[string]*openfgav1.TypeDefinition {
	types := map[string]*openfgav1.TypeDefinition{}

	if node.ResourceType != TypeRoot {
		permissions := hierarchicalPermissions[node.ResourceType]
		if permissions == nil {
			permissions = []string{}
		}
		types[node.ResourceType] = getHybridResourceTypeDefinition(permissions, node)
	}

	for _, child := range node.ChildResources {
		childTypes := getHybridResourceTypeDefinitionsWithHierarchicalPermissions(hierarchicalPermissions, child)
		for k, v := range childTypes {
			types[k] = v
		}
	}

	return types
}

// getHybridRootTypeDefinition builds a Root type that supports both direct
// tuple writes and legacy rolebinding-based resolution. Each hashed permission
// is a union of This (direct) and TupleToUserset(rolebinding) (legacy).
func getHybridRootTypeDefinition(permissions []string, resourceTypes []string) *openfgav1.TypeDefinition {
	sortedPermissions := make([]string, len(permissions))
	copy(sortedPermissions, permissions)
	sort.Strings(sortedPermissions)

	sortedResourceTypes := make([]string, len(resourceTypes))
	copy(sortedResourceTypes, resourceTypes)
	sort.Strings(sortedResourceTypes)

	relationReferences := make([]*openfgav1.RelationReference, 0, len(sortedResourceTypes))
	for _, rt := range sortedResourceTypes {
		relationReferences = append(relationReferences, &openfgav1.RelationReference{Type: rt})
	}

	root := &openfgav1.TypeDefinition{
		Type: TypeRoot,
		Metadata: &openfgav1.Metadata{
			Relations: map[string]*openfgav1.RelationMetadata{
				RelationRoleBinding: {
					DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
						{Type: TypeRoleBinding},
					},
				},
				RelationRootBinding: {
					DirectlyRelatedUserTypes: relationReferences,
				},
			},
			SourceInfo: &openfgav1.SourceInfo{File: SourceFile},
			Module:     Module,
		},
		Relations: map[string]*openfgav1.Userset{
			RelationRoleBinding: {Userset: &openfgav1.Userset_This{}},
			RelationRootBinding: {Userset: &openfgav1.Userset_This{}},
		},
	}

	for _, permission := range sortedPermissions {
		hashedPermission := hashPermission(permission)

		// Metadata: accept direct user/group writes
		root.Metadata.Relations[hashedPermission] = &openfgav1.RelationMetadata{
			DirectlyRelatedUserTypes: []*openfgav1.RelationReference{
				{Type: TypeInternalUser},
				{
					Type: TypeInternalUserGroup,
					RelationOrWildcard: &openfgav1.RelationReference_Relation{
						Relation: RelationMember,
					},
				},
			},
		}

		// Union: direct assignment + legacy rolebinding resolution
		root.Relations[hashedPermission] = &openfgav1.Userset{
			Userset: &openfgav1.Userset_Union{
				Union: &openfgav1.Usersets{
					Child: []*openfgav1.Userset{
						// Direct assignment (new model)
						{Userset: &openfgav1.Userset_This{This: &openfgav1.DirectUserset{}}},
						// Legacy: resolve through RoleBinding chain
						{
							Userset: &openfgav1.Userset_TupleToUserset{
								TupleToUserset: &openfgav1.TupleToUserset{
									Tupleset:        &openfgav1.ObjectRelation{Relation: RelationRoleBinding},
									ComputedUserset: &openfgav1.ObjectRelation{Relation: hashedPermission},
								},
							},
						},
					},
				},
			},
		}
	}

	return root
}
