name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Read golangci-lint version
        id: version
        run: echo "version=$(cat .golangci-version)" >> $GITHUB_OUTPUT

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ steps.version.outputs.version }}
